/**
 * redesign/build.mjs — precompile the redesign at build time.
 *
 * Authoring file: index.dev.html (loads src/*.jsx via @babel/standalone — instant edit/reload, no build).
 * This script produces the SERVED, production index.html:
 *   - transpiles each src/*.jsx -> dist/*.js (same transform babel-standalone did at runtime:
 *     @babel/preset-react for JSX + transform-block-scoping for const/let -> var, so the
 *     top-level `const {useState}=React` in app.jsx & components.jsx coexist as shared globals)
 *   - drops the 640KB @babel/standalone (no in-browser transpile)
 *   - swaps React development -> production builds
 *
 * Run:  npm run build:redesign   (i.e. `node redesign/build.mjs`)
 *
 * Why this exists: the in-browser babel + dev React cost ~26s of JS execution / 21s TBT on a
 * throttled first load (Lighthouse 25/100). Precompiling drops that to ~0.6s exec / 0 TBT (56/100)
 * while rendering an identical DOM. See plannary-engineering-study/results/lighthouse-redesign-*.
 *
 * Modern-browser note: async/optional-chaining etc. are left native (PWA targets modern browsers),
 * unlike babel-standalone's es5 output. Only const/let are lowered (to keep cross-file globals).
 */
import { readFileSync, writeFileSync, mkdirSync, readdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';

const babel = createRequire(import.meta.url)('@babel/core');
const HERE = dirname(fileURLToPath(import.meta.url)); // redesign/
const SRC = join(HERE, 'src');
const DIST = join(HERE, 'dist');
mkdirSync(DIST, { recursive: true });

const jsx = readdirSync(SRC).filter((f) => f.endsWith('.jsx'));
let srcBytes = 0, outBytes = 0;
for (const f of jsx) {
  const code = readFileSync(join(SRC, f), 'utf8');
  const res = babel.transformSync(code, {
    configFile: false, babelrc: false,
    presets: [['@babel/preset-react', { runtime: 'classic' }]],
    plugins: ['@babel/plugin-transform-block-scoping'],
    compact: true, comments: false,
  });
  writeFileSync(join(DIST, f.replace(/\.jsx$/, '.js')), res.code);
  srcBytes += Buffer.byteLength(code);
  outBytes += Buffer.byteLength(res.code);
}

let html = readFileSync(join(HERE, 'index.dev.html'), 'utf8');
// React dev -> prod (drops the now-mismatched SRI hash on those two tags)
html = html.replace(
  'react.development.js" integrity="sha384-hD6/rw4ppMLGNu3tX5cjIb+uRZ7UkRJ6BPkLpg4hAu/6onKUg4lLsHAs9EBPT82L"',
  'react.production.min.js"');
html = html.replace(
  'react-dom.development.js" integrity="sha384-u6aeetuaXnQ38mYT8rp6sbXaQe3NL9t+IBXmnYxwkUI2Hw4bsp2Wvmx4yRQF1uAm"',
  'react-dom.production.min.js"');
// drop @babel/standalone
html = html.replace(/[ \t]*<script src="https:\/\/unpkg\.com\/@babel\/standalone[^>]*><\/script>\n?/, '');
// text/babel src .jsx -> precompiled .js
html = html.replace(
  /<script type="text\/babel" src="\/redesign\/src\/([^"]+)\.jsx"><\/script>/g,
  '<script src="/redesign/dist/$1.js"></script>');
// mark the generated file
html = html.replace('<head>', '<head>\n  <!-- GENERATED by redesign/build.mjs from index.dev.html — do not edit by hand -->');

writeFileSync(join(HERE, 'index.html'), html);
console.log(`[build:redesign] ${jsx.length} files  ${Math.round(srcBytes/1024)}KB jsx -> ${Math.round(outBytes/1024)}KB js  + index.html`);
